name: Deploy to server

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                messsage: ["hola","alog2","algo3"]
        steps: 
            - name: Print mensaje
              run: echo "${{ matrix.messsage}}"
            